-- MySQL Script generated by MySQL Workbench
-- Wed Jan  4 14:12:50 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hospital
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hospital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospital` DEFAULT CHARACTER SET utf8mb3 ;
USE `hospital` ;

-- -----------------------------------------------------
-- Table `hospital`.`branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`branch` (
  `branchid` INT NOT NULL,
  `branchloc` VARCHAR(45) NOT NULL,
  `branchphno` DOUBLE NOT NULL,
  PRIMARY KEY (`branchid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `hospital`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`department` (
  `departmentid` INT NOT NULL,
  `departmentname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`departmentid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `hospital`.`doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`doctor` (
  `doctorid` INT NOT NULL,
  `doctorname` VARCHAR(45) NOT NULL,
  `docphno` DOUBLE NOT NULL,
  `departmentid` INT NOT NULL,
  PRIMARY KEY (`doctorid`),
  INDEX `dept_key_idx` (`departmentid` ASC) VISIBLE,
  CONSTRAINT `dept_key`
    FOREIGN KEY (`departmentid`)
    REFERENCES `hospital`.`department` (`departmentid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `hospital`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`patient` (
  `patientId` INT NOT NULL,
  `patientname` VARCHAR(45) NOT NULL,
  `dob` DATE NOT NULL,
  `gender` VARCHAR(55) NOT NULL,
  `doctorid` INT NOT NULL,
  PRIMARY KEY (`patientId`),
  INDEX `doc_key_idx` (`doctorid` ASC) VISIBLE,
  CONSTRAINT `doc_key`
    FOREIGN KEY (`doctorid`)
    REFERENCES `hospital`.`doctor` (`doctorid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `hospital`.`appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`appointment` (
  `appointmentId` INT NOT NULL,
  `patientId` INT NOT NULL,
  `doctorid` INT NOT NULL,
  `branchid` INT NOT NULL,
  `appointmentdate` DATETIME NOT NULL,
  PRIMARY KEY (`appointmentId`),
  INDEX `patientId_idx` (`patientId` ASC) VISIBLE,
  INDEX `doctorid_idx` (`branchid` ASC) VISIBLE,
  INDEX `doc_key_idx` (`doctorid` ASC) VISIBLE,
  CONSTRAINT `app_branchid`
    FOREIGN KEY (`branchid`)
    REFERENCES `hospital`.`branch` (`branchid`),
  CONSTRAINT `app_doc_key`
    FOREIGN KEY (`doctorid`)
    REFERENCES `hospital`.`doctor` (`doctorid`),
  CONSTRAINT `app_patient`
    FOREIGN KEY (`patientId`)
    REFERENCES `hospital`.`patient` (`patientId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `hospital`.`stay`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`stay` (
  `stayid` INT NOT NULL,
  `patientId` INT NOT NULL,
  `doctorid` INT NOT NULL,
  `branchid` INT NOT NULL,
  `roomid` INT NOT NULL,
  `duration` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`stayid`),
  INDEX `patientId_stay_idx` (`patientId` ASC) VISIBLE,
  INDEX `branchid_stay_idx` (`branchid` ASC) VISIBLE,
  INDEX `stay_doctor_key_idx` (`doctorid` ASC) VISIBLE,
  CONSTRAINT `stay_branch_key`
    FOREIGN KEY (`branchid`)
    REFERENCES `hospital`.`branch` (`branchid`),
  CONSTRAINT `stay_doctor_key`
    FOREIGN KEY (`doctorid`)
    REFERENCES `hospital`.`doctor` (`doctorid`),
  CONSTRAINT `stay_patient_key`
    FOREIGN KEY (`patientId`)
    REFERENCES `hospital`.`patient` (`patientId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
